Writing prometheus metrics to bigquery
tzehon/community pull request #1
Opened 2021-03-08 06:44 UTC by tzehon

For review by jpatokal

2021-03-09 08:36 UTC, jpatokal requested changes

2021-03-09 08:36 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +
Add a brief explanation of what's happening here

2021-03-09 08:36 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. Get the external IP for Prometheus:
Do we really need an external IP for this?

2021-03-09 08:36 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        export SERVICE_IP=`kubectl get svc prometheus --output jsonpath='{.status.loadBalancer.ingress[0].ip}'`
This will silently fail until an external IP is assigned, maybe check that service is up first

2021-03-09 08:36 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        export CLUSTER_NAME=my-cluster
Nit: prom-cluster

2021-03-09 08:36 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. You should see some results:
Also note that you need to hit Ctrl-C to exit or it will tail forever.

2021-03-09 08:36 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. Create a service account that Prometheus will use to write metrics to BigQuery:
Google service account (as opposed to k8s)

2021-03-09 08:36 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        kubectl apply -f custom_prometheus.yaml
Metrics not coming through to BQ, logs for prometheus-prometheus say:

```
caller=main.go:346 msg="Error sending samples to remote storage" err="googleapi: Error 403: Request had insufficient authentication scopes.\nMore details:\nReason: insufficientPermissions, Message: Insufficient Permission\n" storage=bigquerydb num_samples=93
```

2021-03-10 03:06 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        kubectl apply -f custom_prometheus.yaml
PEBKAC, fixed.

2021-03-10 03:12 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. You can also query metrics from Prometheus. Prometheus will query BigQuery remotely, and will merge the returned results with results from local storage for you. Open the Prometheus UI at `http://
Didn't quite follow here: if Prom is configured to use BQ as storage, is there local storage?  If there is, how does it 'know' which one to fetch data from?

2021-03-11 10:58 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +This tutorial describes a solution that uses [Prometheus's](https://prometheus.io/) [remote write integration](https://github.com/KohlsTechnology/prometheus_bigquery_remote_storage_adapter) with [Big
Updated text, and will comment on Kohl's repo when the tutorial is published.

2021-03-11 10:58 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +
Added step.

2021-03-11 10:58 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        export PROJECT_ID=`gcloud config get-value core/project`
Changed.

2021-03-11 10:59 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.46.0/bundle.yaml
I chose this approach so that I can fix the versions declaratively instead of checking out a separate repo and getting the user to check out a specific tag, and work with relative paths. This seems to be more straightforward.  

The k8s documentation examples also use this approach, so I thought it would be more familiar.

2021-03-11 11:00 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. You should see some results:
Merged the steps. However this does terminate when I tried, as /metrics seems to be a bounded response for me, although it's quite laggy because -Cloud Shell-

2021-03-11 11:00 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +
Added

2021-03-11 11:01 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. Get the external IP for Prometheus:
Reverted back to how the Operator guide does it, with a NodePort, so no change needed.

2021-03-11 11:01 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        export SERVICE_IP=`kubectl get svc prometheus --output jsonpath='{.status.loadBalancer.ingress[0].ip}'`
Obsolete as we reverted to the guide's solution of using a NodePort

2021-03-11 11:02 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        export CLUSTER_NAME=my-cluster
Changed

2021-03-11 11:02 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. Create a service account that Prometheus will use to write metrics to BigQuery:
Updated in the latest commit

2021-03-11 11:02 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. You can also query metrics from Prometheus. Prometheus will query BigQuery remotely, and will merge the returned results with results from local storage for you. Open the Prometheus UI at `http://
Updated with how Prometheus does it.

2021-03-12 09:54 UTC, jpatokal reviewed
Basically LGTM, a few more wording tweaks.

2021-03-12 09:54 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. You can also query metrics from Prometheus. When configured, Prometheus queries are sent to both local and remote storage, and the results are merged. In this tutorial, this means that Prometheus
sp: queries

2021-03-12 09:54 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. Return to your terminal and enter `Ctrl-c` to stop port-forwarding. After a few seconds, you can see how Prometheus's BigQuery remote read integration translates this into an intermediate query th
"Prometheus fetches data from BigQuery and displays it.  Return to your...  After a few seconds, you can check Cloud Logging to see the actual query used by Prometheus's BigQuery remote read integration."

2021-03-12 09:54 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +        kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.46.0/bundle.yaml
Ack

2021-03-12 09:57 UTC, jpatokal commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. In the new terminal, check that you have deployed Prometheus successfully:
AFAICT this is the first mention of a new terminal?  Please note how to create it (plus tab in Cloud Shell)

2021-03-16 04:54 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. Return to your terminal and enter `Ctrl-c` to stop port-forwarding. After a few seconds, you can see how Prometheus's BigQuery remote read integration translates this into an intermediate query th
Updated

2021-03-16 04:54 UTC, tzehon commented on tutorials/writing-prometheus-metrics-bigquery/index.md
> +1. You can also query metrics from Prometheus. When configured, Prometheus queries are sent to both local and remote storage, and the results are merged. In this tutorial, this means that Prometheus
Fixed

2021-03-18 06:19 UTC, tzehon commented
Closing PR after peer review. Starting process to merge into upstream.

2021-03-18 06:19 UTC, closed without merging